# Generated by Django 3.2.1 on 2022-12-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='邀请码')),
                ('expire', models.DateTimeField(verbose_name='过期时间')),
            ],
        ),
    ]
